package at.tug.oad.travelsales.utils;

/**
 * @author Leopold Christian - 1331948
 * 23.11.2014 - 23:04:47
 * 
 */
public enum TSExceptionType {
	INTERNAL_ERROR,
	INVALID_MAIL_ADDRESS,
	INVALID_PASSWORD,
	ACCOUNT_NAME_ALREADY_IN_USE,
	INVALID_FILE,
	PASSWORD_ALREADY_RESETED,
	USER_IS_ALREADY_IN_FRIEND_LIST,
	FRIEND_LIST_INVITATION_PENDING,
	USER_DOES_NOT_EXIST_IN_DATABASE,
	;
}
