/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates and open the template
 * in the editor.
 */
package at.tug.oad.travelsales.view.gui;

import javax.swing.JFileChooser;

import at.tug.oad.travelsales.controller.TravelSalesViewController;
import at.tug.oad.travelsales.model.IBaseGame;
import at.tug.oad.travelsales.view.state.EditState;

/**
 *
 * @author Martin
 */
public class Edit_BaseGame_Panel extends javax.swing.JPanel {
	private IBaseGame game;

	/**
	 * Creates new form Edit_BaseGame
	 */
	public Edit_BaseGame_Panel() {
		initComponents();
		pnGame.setPointInfoPanel(this.pointInfoPanel1);
		changeState(EditState.SELECT_POINT);
	}

	public void setBaseGame(IBaseGame game) {
		this.game = game;
		tfBaseGameName.setText(game.getName());
		pnGame.setGame(game);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		bgPointActions = new javax.swing.ButtonGroup();
		jPanel1 = new javax.swing.JPanel();
		pnBackground = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		tfImagePath = new javax.swing.JTextField();
		btDurchsuchen = new javax.swing.JButton();
		btChangeBackground = new javax.swing.JButton();
		pnPoints = new javax.swing.JPanel();
		rbNewPoint = new javax.swing.JRadioButton();
		rbSelectPoint = new javax.swing.JRadioButton();
		rbDeletePoint = new javax.swing.JRadioButton();
		pointInfoPanel1 = new at.tug.oad.travelsales.view.gui.PointInfoPanel();
		pnInfos = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		tfBaseGameName = new javax.swing.JTextField();
		jButton2 = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		pnGame = new at.tug.oad.travelsales.view.gui.EditBaseGamePanel();
		jPanel4 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();

		setLayout(new java.awt.BorderLayout());

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Actions:"));
		jPanel1.setLayout(new java.awt.BorderLayout());

		pnBackground.setBorder(javax.swing.BorderFactory.createTitledBorder("Change Background:"));
		pnBackground.setLayout(new java.awt.GridBagLayout());

		jLabel1.setText("Please select an image:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		pnBackground.add(jLabel1, gridBagConstraints);

		tfImagePath.setColumns(27);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		pnBackground.add(tfImagePath, gridBagConstraints);

		btDurchsuchen.setText("...");
		btDurchsuchen.setMaximumSize(new java.awt.Dimension(25, 23));
		btDurchsuchen.setMinimumSize(new java.awt.Dimension(25, 23));
		btDurchsuchen.setPreferredSize(new java.awt.Dimension(25, 23));
		btDurchsuchen.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onSearchImage(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		pnBackground.add(btDurchsuchen, gridBagConstraints);

		btChangeBackground.setText("Change background");
		btChangeBackground.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onChangeBackground(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.gridwidth = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.weightx = 0.1;
		gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
		pnBackground.add(btChangeBackground, gridBagConstraints);

		jPanel1.add(pnBackground, java.awt.BorderLayout.SOUTH);

		pnPoints.setBorder(javax.swing.BorderFactory.createTitledBorder("Points:"));
		pnPoints.setLayout(new java.awt.GridBagLayout());

		bgPointActions.add(rbNewPoint);
		rbNewPoint.setText("Place new Point");
		rbNewPoint.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onRbNewPoint(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		pnPoints.add(rbNewPoint, gridBagConstraints);

		bgPointActions.add(rbSelectPoint);
		rbSelectPoint.setSelected(true);
		rbSelectPoint.setText("Select Point");
		rbSelectPoint.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onRbSelectPoint(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		pnPoints.add(rbSelectPoint, gridBagConstraints);

		bgPointActions.add(rbDeletePoint);
		rbDeletePoint.setText("Delete Point");
		rbDeletePoint.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onRbDeletePoint(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		pnPoints.add(rbDeletePoint, gridBagConstraints);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 4;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		pnPoints.add(pointInfoPanel1, gridBagConstraints);

		jPanel1.add(pnPoints, java.awt.BorderLayout.CENTER);

		pnInfos.setBorder(javax.swing.BorderFactory.createTitledBorder("Infos:"));
		pnInfos.setLayout(new java.awt.GridBagLayout());

		jLabel2.setText("Name of BaseGame:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 6);
		pnInfos.add(jLabel2, gridBagConstraints);

		tfBaseGameName.setColumns(15);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		pnInfos.add(tfBaseGameName, gridBagConstraints);

		jButton2.setText("Save");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onSaveBaseGameName(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
		pnInfos.add(jButton2, gridBagConstraints);

		jPanel1.add(pnInfos, java.awt.BorderLayout.PAGE_START);

		add(jPanel1, java.awt.BorderLayout.WEST);

		jPanel2.setLayout(new java.awt.BorderLayout());

		javax.swing.GroupLayout pnGameLayout = new javax.swing.GroupLayout(pnGame);
		pnGame.setLayout(pnGameLayout);
		pnGameLayout.setHorizontalGroup(pnGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 327, Short.MAX_VALUE));
		pnGameLayout.setVerticalGroup(pnGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 410, Short.MAX_VALUE));

		jPanel2.add(pnGame, java.awt.BorderLayout.CENTER);

		add(jPanel2, java.awt.BorderLayout.CENTER);

		jButton1.setText("Finished & Back");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onBack(evt);
			}
		});
		jPanel4.add(jButton1);

		add(jPanel4, java.awt.BorderLayout.SOUTH);
	}// </editor-fold>//GEN-END:initComponents

	private void onRbNewPoint(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_onRbNewPoint
		changeState(EditState.NEW_POINT);
	}// GEN-LAST:event_onRbNewPoint

	private void onRbSelectPoint(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_onRbSelectPoint
		changeState(EditState.SELECT_POINT);
	}// GEN-LAST:event_onRbSelectPoint

	private void onRbDeletePoint(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_onRbDeletePoint
		changeState(EditState.DELETE_POINT);
	}// GEN-LAST:event_onRbDeletePoint

	private void onSearchImage(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_onSearchImage
		JFileChooser chooser = new JFileChooser(tfImagePath.getText());
		int answ = chooser.showOpenDialog(this);
		if (answ == JFileChooser.APPROVE_OPTION) {
			tfImagePath.setText(chooser.getSelectedFile().getPath());
			game.setFigurePath(chooser.getSelectedFile().getPath());
		}
	}// GEN-LAST:event_onSearchImage

	private void onChangeBackground(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_onChangeBackground
		TravelSalesViewController.getInstance().editBaseGame(game, g -> g.setFigurePath(tfImagePath.getText()));
		pnGame.setGame(game);
		pnGame.updateUI(); // draw again
	}// GEN-LAST:event_onChangeBackground

	private void onBack(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_onBack
		TravelSalesViewController.getInstance().cancel(); // Back to last state
	}// GEN-LAST:event_onBack

	private void onSaveBaseGameName(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_onSaveBaseGameName
		TravelSalesViewController.getInstance().editBaseGame(game, g -> g.setName(tfBaseGameName.getText()));
	}// GEN-LAST:event_onSaveBaseGameName

	private void changeState(EditState state) {
		this.pnGame.setEditState(state);
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.ButtonGroup bgPointActions;
	private javax.swing.JButton btChangeBackground;
	private javax.swing.JButton btDurchsuchen;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel pnBackground;
	private at.tug.oad.travelsales.view.gui.EditBaseGamePanel pnGame;
	private javax.swing.JPanel pnInfos;
	private javax.swing.JPanel pnPoints;
	private at.tug.oad.travelsales.view.gui.PointInfoPanel pointInfoPanel1;
	private javax.swing.JRadioButton rbDeletePoint;
	private javax.swing.JRadioButton rbNewPoint;
	private javax.swing.JRadioButton rbSelectPoint;
	private javax.swing.JTextField tfBaseGameName;
	private javax.swing.JTextField tfImagePath;
	// End of variables declaration//GEN-END:variables
}
