/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates and open the template
 * in the editor.
 */
package at.tug.oad.travelsales.view.gui;

import java.text.SimpleDateFormat;

import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

import at.tug.oad.travelsales.controller.TravelSalesViewController;
import at.tug.oad.travelsales.model.IGame;
import at.tug.oad.travelsales.model.ILevel;
import at.tug.oad.travelsales.utils.TSExceptionType;
import at.tug.oad.travelsales.utils.TravelSalesException;

/**
 *
 * @author Martin
 */
public class EditGamePanel extends javax.swing.JPanel {
	private IGame game;
	private DefaultListModel model;
	private ILevel selectedLevel;

	/**
	 * Creates new form EditGamePanel
	 */
	public EditGamePanel() {
		initComponents();
	}

	public void setGame(IGame game) {
		if (game == null)
			return;

		this.game = game;
		updateInformation();
	}

	private void updateInformation() {
		tfName.setText(game.getName());
		tfIconPath.setText(game.getLogoPath());
		tfCreator.setText(game.getCreator().getUserName());
		SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
		tfCreationDate.setText(sdf.format(game.getCreateDate()));

		model = new DefaultListModel();
		liLevels.setModel(model);

		for (ILevel lvl : game.getNestedCollection()) {
			model.addElement(lvl.getName());
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		jPanel1 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		liLevels = new javax.swing.JList();
		jPanel4 = new javax.swing.JPanel();
		jButton4 = new javax.swing.JButton();
		jButton5 = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		tfName = new javax.swing.JTextField();
		tfIconPath = new javax.swing.JTextField();
		tfCreator = new javax.swing.JTextField();
		tfCreationDate = new javax.swing.JTextField();
		jPanel3 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();

		setLayout(new java.awt.BorderLayout());

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Levels:"));
		jPanel1.setLayout(new java.awt.BorderLayout());

		liLevels.setModel(new javax.swing.AbstractListModel() {
			String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		liLevels.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
			public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
				onListValurChanged(evt);
			}
		});
		jScrollPane1.setViewportView(liLevels);

		jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

		jPanel4.setLayout(new java.awt.GridBagLayout());

		jButton4.setText("Delete selected");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onDeleteSelectedLevel(evt);
			}
		});
		jPanel4.add(jButton4, new java.awt.GridBagConstraints());

		jButton5.setText("Add New");
		jButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onAddNewLevel(evt);
			}
		});
		jPanel4.add(jButton5, new java.awt.GridBagConstraints());

		jPanel1.add(jPanel4, java.awt.BorderLayout.SOUTH);

		add(jPanel1, java.awt.BorderLayout.CENTER);

		jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Game Information:"));
		jPanel2.setLayout(new java.awt.GridBagLayout());

		jLabel1.setText("Name:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 7);
		jPanel2.add(jLabel1, gridBagConstraints);

		jLabel2.setText("Icon Path:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 7);
		jPanel2.add(jLabel2, gridBagConstraints);

		jLabel3.setText("Creator:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 7);
		jPanel2.add(jLabel3, gridBagConstraints);

		jLabel4.setText("Creation date:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 7);
		jPanel2.add(jLabel4, gridBagConstraints);

		jButton2.setText("Save");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onSave(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 4;
		gridBagConstraints.gridwidth = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(7, 2, 2, 2);
		jPanel2.add(jButton2, gridBagConstraints);

		jButton3.setText("...");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onSearch(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		jPanel2.add(jButton3, gridBagConstraints);

		tfName.setColumns(20);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridwidth = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		jPanel2.add(tfName, gridBagConstraints);

		tfIconPath.setColumns(20);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		jPanel2.add(tfIconPath, gridBagConstraints);

		tfCreator.setEditable(false);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.gridwidth = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		jPanel2.add(tfCreator, gridBagConstraints);

		tfCreationDate.setEditable(false);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.gridwidth = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
		jPanel2.add(tfCreationDate, gridBagConstraints);

		add(jPanel2, java.awt.BorderLayout.PAGE_START);

		jButton1.setText("Back");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onBack(evt);
			}
		});
		jPanel3.add(jButton1);

		add(jPanel3, java.awt.BorderLayout.PAGE_END);
	}// </editor-fold>//GEN-END:initComponents

	private void onSearch(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_onSearch
		try {
			JFileChooser chooser = new JFileChooser(tfIconPath.getText());
			if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
				tfIconPath.setText(chooser.getSelectedFile().getCanonicalPath());
			}
		} catch (Exception e) {
			TravelSalesViewController.getInstance().showMessageDialog("Error", e.getMessage(), MessageType.ERROR);
		}
	}// GEN-LAST:event_onSearch

	private void onSave(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_onSave
		TravelSalesViewController.getInstance().editGame(game, g -> {
			g.setName(tfName.getText());
			g.setLogoPath(tfIconPath.getText());
		});
	}// GEN-LAST:event_onSave

	private void onAddNewLevel(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_onAddNewLevel
		ILevel newLevel = TravelSalesViewController.getInstance().newLevel("New Level");
		TravelSalesViewController.getInstance().editGame(game, l -> l.add(newLevel));
		TravelSalesViewController.getInstance().showMessageDialog("Success", "New Level created!\nYou can edit Levels in the edit-screen.", MessageType.SUCCESS);

		updateInformation();
	}// GEN-LAST:event_onAddNewLevel

	private void onListValurChanged(javax.swing.event.ListSelectionEvent evt) {// GEN-FIRST:event_onListValurChanged
		int index = liLevels.getSelectedIndex();
		if (index < 0) {
			return;
		}

		selectedLevel = game.getNestedCollection().get(index);
	}// GEN-LAST:event_onListValurChanged

	private void onDeleteSelectedLevel(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_onDeleteSelectedLevel
		try {
			if (selectedLevel == null)
				throw new TravelSalesException(TSExceptionType.INTERNAL_ERROR, "No level selected!");

			String question = selectedLevel.getName() + " will be deleted! Continue?";

			int a = JOptionPane.showConfirmDialog(this, question, "Please confirm", JOptionPane.YES_NO_OPTION);
			if (a == JOptionPane.YES_OPTION) {
				TravelSalesViewController.getInstance().editGame(game, l -> l.remove(selectedLevel));
			}
		} catch (Exception e) {
			TravelSalesViewController.getInstance().showMessageDialog("Error", e.getLocalizedMessage(), MessageType.ERROR);
		}
	}// GEN-LAST:event_onDeleteSelectedLevel

	private void onBack(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_onBack
		TravelSalesViewController.getInstance().cancel();
	}// GEN-LAST:event_onBack

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JList liLevels;
	private javax.swing.JTextField tfCreationDate;
	private javax.swing.JTextField tfCreator;
	private javax.swing.JTextField tfIconPath;
	private javax.swing.JTextField tfName;
	// End of variables declaration//GEN-END:variables
}
