/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates and open the template
 * in the editor.
 */
package at.tug.oad.travelsales.view.gui;

import java.text.SimpleDateFormat;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

import at.tug.oad.travelsales.controller.TravelSalesViewController;
import at.tug.oad.travelsales.model.IBaseGame;
import at.tug.oad.travelsales.model.ILevel;

/**
 *
 * @author Martin
 */
public class EditLevelPanel extends javax.swing.JPanel {

	private ILevel level;
	private DefaultListModel model;

	private IBaseGame selectedBaseGame;

	/**
	 * Creates new form EditLevelPanel
	 */
	public EditLevelPanel() {
		initComponents();
	}

	public void setLevel(ILevel level) {
		this.level = level;

		updateInformation();
	}

	private void updateInformation() {
		if (level == null) {
			return;
		}
		SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
		tfName.setText(level.getName());
		tfCreator.setText(level.getCreator().getUserName());
		tfCreationDate.setText(sdf.format(level.getCreateDate()));
		model = new DefaultListModel();
		liBaseGames.setModel(model);
		for (IBaseGame bgame : level.getNestedCollection()) {
			model.addElement(bgame.getName());
		}

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		pnCenter = new javax.swing.JPanel();
		pnInfo = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		tfName = new javax.swing.JTextField();
		tfCreator = new javax.swing.JTextField();
		tfCreationDate = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		pnBaseGames = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		liBaseGames = new javax.swing.JList();
		pnListActions = new javax.swing.JPanel();
		jScrollPane2 = new javax.swing.JScrollPane();
		taDescription = new javax.swing.JTextArea();
		jPanel1 = new javax.swing.JPanel();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jPanel2 = new javax.swing.JPanel();
		jButton4 = new javax.swing.JButton();

		setLayout(new java.awt.BorderLayout());

		pnCenter.setLayout(new java.awt.BorderLayout());

		pnInfo.setBorder(javax.swing.BorderFactory.createTitledBorder("Level Information:"));
		pnInfo.setLayout(new java.awt.GridBagLayout());

		jLabel1.setText("Name:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
		pnInfo.add(jLabel1, gridBagConstraints);

		jLabel2.setText("Creator:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
		pnInfo.add(jLabel2, gridBagConstraints);

		jLabel3.setText("Created:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
		pnInfo.add(jLabel3, gridBagConstraints);

		tfName.setColumns(20);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(0, 6, 3, 0);
		pnInfo.add(tfName, gridBagConstraints);

		tfCreator.setEditable(false);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(0, 6, 3, 0);
		pnInfo.add(tfCreator, gridBagConstraints);

		tfCreationDate.setEditable(false);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(0, 6, 3, 0);
		pnInfo.add(tfCreationDate, gridBagConstraints);

		jButton1.setText("Save");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onSaveName(evt);
			}
		});
		pnInfo.add(jButton1, new java.awt.GridBagConstraints());

		pnCenter.add(pnInfo, java.awt.BorderLayout.NORTH);

		pnBaseGames.setBorder(javax.swing.BorderFactory.createTitledBorder("Base-Games:"));
		pnBaseGames.setLayout(new java.awt.GridLayout(1, 0));

		liBaseGames.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
			public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
				onListValueChanged(evt);
			}
		});
		jScrollPane1.setViewportView(liBaseGames);

		pnBaseGames.add(jScrollPane1);

		pnListActions.setLayout(new java.awt.BorderLayout());

		taDescription.setEditable(false);
		taDescription.setColumns(20);
		taDescription.setRows(5);
		jScrollPane2.setViewportView(taDescription);

		pnListActions.add(jScrollPane2, java.awt.BorderLayout.CENTER);

		jButton2.setText("Delete selected");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onDeleteBaseGame(evt);
			}
		});
		jPanel1.add(jButton2);

		jButton3.setText("Add new");
		jButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onAddNewBaseGame(evt);
			}
		});
		jPanel1.add(jButton3);

		pnListActions.add(jPanel1, java.awt.BorderLayout.SOUTH);

		pnBaseGames.add(pnListActions);

		pnCenter.add(pnBaseGames, java.awt.BorderLayout.CENTER);

		add(pnCenter, java.awt.BorderLayout.CENTER);

		jButton4.setText("Back");
		jButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onBack(evt);
			}
		});
		jPanel2.add(jButton4);

		add(jPanel2, java.awt.BorderLayout.SOUTH);
	}// </editor-fold>//GEN-END:initComponents

	private void onListValueChanged(javax.swing.event.ListSelectionEvent evt) {// GEN-FIRST:event_onListValueChanged
		int index = liBaseGames.getSelectedIndex();
		if (index < 0) {
			return;
		}

		selectedBaseGame = level.getNestedCollection().get(index);
		taDescription.setText(selectedBaseGame.toString());
	}// GEN-LAST:event_onListValueChanged

	private void onAddNewBaseGame(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_onAddNewBaseGame
		IBaseGame newBaseGame = TravelSalesViewController.getInstance().newBaseGame("New BaseGame");
		TravelSalesViewController.getInstance().editLevel(level, l -> l.add(newBaseGame));
		TravelSalesViewController.getInstance().showMessageDialog("Success", "New Base-Game created!\nYou can edit Base-Games in the edit-screen.", MessageType.SUCCESS);

		updateInformation();
	}// GEN-LAST:event_onAddNewBaseGame

	private void onDeleteBaseGame(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_onDeleteBaseGame
		String question = selectedBaseGame.getName() + " will be deleted! Continue?";

		int a = JOptionPane.showConfirmDialog(this, question, "Please confirm", JOptionPane.YES_NO_OPTION);
		if (a == JOptionPane.YES_OPTION) {
			TravelSalesViewController.getInstance().editLevel(level, l -> l.remove(selectedBaseGame));
		}
	}// GEN-LAST:event_onDeleteBaseGame

	private void onSaveName(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_onSaveName
		TravelSalesViewController.getInstance().editLevel(level, l -> l.setName(tfName.getText()));
	}// GEN-LAST:event_onSaveName

	private void onBack(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_onBack
		TravelSalesViewController.getInstance().cancel();
	}// GEN-LAST:event_onBack

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JList liBaseGames;
	private javax.swing.JPanel pnBaseGames;
	private javax.swing.JPanel pnCenter;
	private javax.swing.JPanel pnInfo;
	private javax.swing.JPanel pnListActions;
	private javax.swing.JTextArea taDescription;
	private javax.swing.JTextField tfCreationDate;
	private javax.swing.JTextField tfCreator;
	private javax.swing.JTextField tfName;
	// End of variables declaration//GEN-END:variables
}
