/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates and open the template
 * in the editor.
 */
package at.tug.oad.travelsales.view.gui;

import java.awt.FlowLayout;
import java.util.Collection;

import javax.swing.JPanel;

import at.tug.oad.travelsales.model.IBaseGame;
import at.tug.oad.travelsales.model.IGame;
import at.tug.oad.travelsales.model.ILevel;

/**
 *
 * @author Martin
 */
public class GameView extends javax.swing.JPanel {

	private Collection<IGame> games;
	private Collection<ILevel> levels;
	private Collection<IBaseGame> basegames;

	/**
	 * Creates new form GameView
	 */
	public GameView() {
		initComponents();
	}

	public void setGames(Collection<IGame> games) {
		this.games = games;
		levels = null;
		basegames = null;
		updateView();
	}

	public void setLevels(Collection<ILevel> levels) {
		this.levels = levels;
		games = null;
		basegames = null;
		updateView();
	}

	public void setBaseGames(Collection<IBaseGame> basegames) {
		this.basegames = basegames;
		games = null;
		levels = null;
		updateView();
	}

	private void updateView() {
		// pnGames.removeAll();

		int cnt = 0;
		JPanel row = new JPanel(new FlowLayout(FlowLayout.LEFT));
		if (games != null) {
			for (IGame game : games) {
				if (cnt % 4 == 0) {
					pnGames.add(row);
					row = new JPanel(new FlowLayout(FlowLayout.LEFT));
				}
				GameButton button = new GameButton(game);
				row.add(button);
				cnt++;
			}
		} else if (levels != null) {
			pnGames.removeAll();
			for (ILevel level : levels) {
				if (cnt % 4 == 0) {
					pnGames.add(row);
					row = new JPanel(new FlowLayout(FlowLayout.LEFT));
				}
				GameButton button = new GameButton(level);
				row.add(button);
				cnt++;
			}
		} else {
			pnGames.removeAll();
			for (IBaseGame basegame : basegames) {
				if (cnt % 4 == 0) {
					pnGames.add(row);
					row = new JPanel(new FlowLayout(FlowLayout.LEFT));
				}
				GameButton button = new GameButton(basegame);
				row.add(button);
				cnt++;
			}
		}
		pnGames.add(row);
		pnGames.updateUI();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		spGames = new javax.swing.JScrollPane();
		pnGames = new javax.swing.JPanel();

		setLayout(new java.awt.BorderLayout());

		pnGames.setLayout(new javax.swing.BoxLayout(pnGames, javax.swing.BoxLayout.Y_AXIS));
		spGames.setViewportView(pnGames);

		add(spGames, java.awt.BorderLayout.CENTER);
	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JPanel pnGames;
	private javax.swing.JScrollPane spGames;
	// End of variables declaration//GEN-END:variables
}
