/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates and open the template
 * in the editor.
 */
package at.tug.oad.travelsales.view.gui;

import java.awt.event.KeyEvent;

import at.tug.oad.travelsales.controller.TravelSalesViewController;

/**
 *
 * @author Martin
 */
public class LoginPanel extends javax.swing.JPanel {

	/**
	 * Creates new form LoginPanel
	 */
	public LoginPanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		tfUsername = new javax.swing.JTextField();
		pfPassword = new javax.swing.JPasswordField();
		jLabel3 = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jPanel4 = new javax.swing.JPanel();
		btLogin = new javax.swing.JButton();
		jPanel3 = new javax.swing.JPanel();
		btRegistration = new javax.swing.JButton();

		setLayout(new java.awt.BorderLayout());

		jPanel1.setLayout(new java.awt.GridBagLayout());

		jLabel1.setText("Username:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
		jPanel1.add(jLabel1, gridBagConstraints);

		jLabel2.setText("Password:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
		jPanel1.add(jLabel2, gridBagConstraints);

		tfUsername.setColumns(20);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
		jPanel1.add(tfUsername, gridBagConstraints);

		pfPassword.addKeyListener(new java.awt.event.KeyAdapter() {
			public void keyPressed(java.awt.event.KeyEvent evt) {
				onPasswordKeyPressed(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
		jPanel1.add(pfPassword, gridBagConstraints);

		jLabel3.setForeground(new java.awt.Color(0, 0, 255));
		jLabel3.setText("<HTML><U>Forgot password?</U></HTML>");
		jLabel3.setToolTipText("Klick here, to reset your password!");
		jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
		jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				onResetPassword(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
		jPanel1.add(jLabel3, gridBagConstraints);

		add(jPanel1, java.awt.BorderLayout.CENTER);

		jPanel2.setLayout(new java.awt.BorderLayout());

		jPanel4.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

		btLogin.setText("Login");
		btLogin.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btLoginonLogin(evt);
			}
		});
		jPanel4.add(btLogin);

		jPanel2.add(jPanel4, java.awt.BorderLayout.WEST);

		jPanel3.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

		btRegistration.setText("Registration");
		btRegistration.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btRegistrationonRegistrate(evt);
			}
		});
		jPanel3.add(btRegistration);

		jPanel2.add(jPanel3, java.awt.BorderLayout.EAST);

		add(jPanel2, java.awt.BorderLayout.SOUTH);
	}// </editor-fold>//GEN-END:initComponents

	private void btLoginonLogin(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btLoginonLogin
		TravelSalesViewController.getInstance().login(tfUsername.getText(), new String(pfPassword.getPassword())); // ->
																													// LC,
																													// compile
																													// error
	}// GEN-LAST:event_btLoginonLogin

	private void btRegistrationonRegistrate(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btRegistrationonRegistrate
		TravelSalesViewController.getInstance().registrate();
	}// GEN-LAST:event_btRegistrationonRegistrate

	/**
	 * If user enters passwird and hits ENTER -> Login-Button simulated
	 * 
	 * @param evt
	 */
	private void onPasswordKeyPressed(java.awt.event.KeyEvent evt) {// GEN-FIRST:event_onPasswordKeyPressed
		if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
			btLogin.doClick();
		}
	}// GEN-LAST:event_onPasswordKeyPressed

	private void onResetPassword(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_onResetPassword
		TravelSalesViewController.getInstance().forgotPassword();
	}// GEN-LAST:event_onResetPassword

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btLogin;
	private javax.swing.JButton btRegistration;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPasswordField pfPassword;
	private javax.swing.JTextField tfUsername;
	// End of variables declaration//GEN-END:variables
}
