/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates and open the template
 * in the editor.
 */
package at.tug.oad.travelsales.view.gui;

import java.util.Collection;

import javax.swing.DefaultListModel;

import at.tug.oad.travelsales.controller.TravelSalesViewController;
import at.tug.oad.travelsales.model.INotification;

/**
 *
 * @author Martin
 */
public class MessagePanel extends javax.swing.JPanel {

	private Collection<INotification> messages;
	private DefaultListModel model;

	/**
	 * Creates new form MessagePanel
	 */
	public MessagePanel() {
		initComponents();
	}

	public void setMessages(Collection<INotification> messages) {
		this.messages = messages;

		updateInformation();
	}

	private void updateInformation() {
		if (messages == null) {
			return;
		}
		model = new DefaultListModel();
		liMessages.setModel(model);

		for (INotification m : messages) {
			String showString = "";
			if (m.getReadTime() == null) // message unread
			{
				showString += "*  ";
			} else {
				showString += "   ";
			}

			showString += "From: ";
			showString += m.getSender().getUserName();
			showString += " (Type: " + m.getNotificationType().toString() + ")";

			model.addElement(showString);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jScrollPane2 = new javax.swing.JScrollPane();
		taText = new javax.swing.JTextArea();
		jPanel3 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jScrollPane1 = new javax.swing.JScrollPane();
		liMessages = new javax.swing.JList();
		jLabel1 = new javax.swing.JLabel();
		jPanel4 = new javax.swing.JPanel();
		jButton2 = new javax.swing.JButton();

		setLayout(new java.awt.BorderLayout());

		jPanel1.setLayout(new java.awt.BorderLayout());

		jPanel2.setLayout(new java.awt.BorderLayout());

		taText.setColumns(20);
		taText.setRows(5);
		jScrollPane2.setViewportView(taText);

		jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

		jButton1.setText("Send new message...");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onNewMessage(evt);
			}
		});
		jPanel3.add(jButton1);

		jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_END);

		jPanel1.add(jPanel2, java.awt.BorderLayout.LINE_END);

		liMessages.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
			public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
				onListValueChanged(evt);
			}
		});
		jScrollPane1.setViewportView(liMessages);

		jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

		jLabel1.setText("Please select a message:");
		jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

		jButton2.setText("Back");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onBack(evt);
			}
		});
		jPanel4.add(jButton2);

		jPanel1.add(jPanel4, java.awt.BorderLayout.PAGE_END);

		add(jPanel1, java.awt.BorderLayout.CENTER);
	}// </editor-fold>//GEN-END:initComponents

	private void onListValueChanged(javax.swing.event.ListSelectionEvent evt) {// GEN-FIRST:event_onListValueChanged
		int index = liMessages.getSelectedIndex();
		if (index < 0) {
			taText.setText("");
			return;
		}
		INotification message = ((INotification[]) messages.toArray())[index];
		taText.setText(TravelSalesViewController.getInstance().readMessage(message));
	}// GEN-LAST:event_onListValueChanged

	private void onNewMessage(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_onNewMessage
		NewMessageDlg dlg = new NewMessageDlg(null, true);
		dlg.setVisible(true);
	}// GEN-LAST:event_onNewMessage

	private void onBack(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_onBack
		TravelSalesViewController.getInstance().cancel();
	}// GEN-LAST:event_onBack

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JList liMessages;
	private javax.swing.JTextArea taText;
	// End of variables declaration//GEN-END:variables
}
