/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates and open the template
 * in the editor.
 */
package at.tug.oad.travelsales.view.gui;

import javax.swing.JFileChooser;

import at.tug.oad.travelsales.controller.TravelSalesViewController;

/**
 *
 * @author Martin
 */
public class newGamePanel extends javax.swing.JPanel {

	/**
	 * Creates new form newGamePanel
	 */
	public newGamePanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		pnCenter = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		tfName = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		cbVisible = new javax.swing.JCheckBox();
		jPanel1 = new javax.swing.JPanel();
		tfLogoPath = new javax.swing.JTextField();
		btDurchsuchen = new javax.swing.JButton();
		pnSouth = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setLayout(new java.awt.BorderLayout());

		pnCenter.setLayout(new java.awt.GridBagLayout());

		jLabel1.setText("Name:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
		pnCenter.add(jLabel1, gridBagConstraints);

		tfName.setColumns(20);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 0;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
		pnCenter.add(tfName, gridBagConstraints);

		jLabel2.setText("Logo path:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
		pnCenter.add(jLabel2, gridBagConstraints);

		cbVisible.setText("Visible for all users");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 5);
		pnCenter.add(cbVisible, gridBagConstraints);

		jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 0, 5));

		tfLogoPath.setColumns(15);
		jPanel1.add(tfLogoPath);

		btDurchsuchen.setText("...");
		btDurchsuchen.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onChangePath(evt);
			}
		});
		jPanel1.add(btDurchsuchen);

		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		pnCenter.add(jPanel1, gridBagConstraints);

		add(pnCenter, java.awt.BorderLayout.CENTER);

		jButton1.setText("Save");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onSave(evt);
			}
		});
		pnSouth.add(jButton1);

		jButton2.setText("Cancel");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onCancel(evt);
			}
		});
		pnSouth.add(jButton2);

		add(pnSouth, java.awt.BorderLayout.SOUTH);
	}// </editor-fold>//GEN-END:initComponents

	private void onCancel(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_onCancel
		TravelSalesViewController.getInstance().cancel();
	}// GEN-LAST:event_onCancel

	private void onSave(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_onSave
		TravelSalesViewController.getInstance().newGame(tfName.getText(), tfLogoPath.getText(), cbVisible.isSelected());
	}// GEN-LAST:event_onSave

	private void onChangePath(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_onChangePath
		JFileChooser chooser = new JFileChooser();
		if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
			tfLogoPath.setText(chooser.getSelectedFile().getPath());
		}
	}// GEN-LAST:event_onChangePath

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btDurchsuchen;
	private javax.swing.JCheckBox cbVisible;
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel pnCenter;
	private javax.swing.JPanel pnSouth;
	private javax.swing.JTextField tfLogoPath;
	private javax.swing.JTextField tfName;
	// End of variables declaration//GEN-END:variables
}
