/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates and open the template
 * in the editor.
 */
package at.tug.oad.travelsales.view.gui;

import at.tug.oad.travelsales.controller.TravelSalesViewController;
import at.tug.oad.travelsales.model.IBaseGame;
import at.tug.oad.travelsales.model.IPlayStatistic;

/**
 *
 * @author Martin
 */
public class PlayGamePanel extends javax.swing.JPanel {

	/**
	 * Creates new form PlayGamePanel
	 */
	public PlayGamePanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		pnCenter = new javax.swing.JPanel();
		pnGame = new javax.swing.JPanel();
		pnPoints = new at.tug.oad.travelsales.view.gui.GamePanel();
		pnHighscore = new javax.swing.JPanel();
		lbLength = new javax.swing.JLabel();
		lbHighscore = new javax.swing.JLabel();
		pnWest = new javax.swing.JPanel();
		pnButtons = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		pnConstrains = new javax.swing.JPanel();

		setLayout(new java.awt.BorderLayout());

		pnCenter.setLayout(new java.awt.BorderLayout());

		pnGame.setLayout(new java.awt.BorderLayout());
		pnGame.add(pnPoints, java.awt.BorderLayout.CENTER);

		pnCenter.add(pnGame, java.awt.BorderLayout.CENTER);

		pnHighscore.setBorder(javax.swing.BorderFactory.createTitledBorder("Highscore:"));
		java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0);
		flowLayout1.setAlignOnBaseline(true);
		pnHighscore.setLayout(flowLayout1);

		lbLength.setText("Length:");
		pnHighscore.add(lbLength);
		pnHighscore.add(lbHighscore);

		pnCenter.add(pnHighscore, java.awt.BorderLayout.NORTH);

		add(pnCenter, java.awt.BorderLayout.CENTER);

		pnWest.setLayout(new java.awt.BorderLayout());

		jButton1.setText("Quit");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onQuit(evt);
			}
		});
		pnButtons.add(jButton1);

		jButton2.setText("Restart");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onRestart(evt);
			}
		});
		pnButtons.add(jButton2);

		pnWest.add(pnButtons, java.awt.BorderLayout.NORTH);

		pnConstrains.setLayout(new javax.swing.BoxLayout(pnConstrains, javax.swing.BoxLayout.LINE_AXIS));
		pnWest.add(pnConstrains, java.awt.BorderLayout.CENTER);

		add(pnWest, java.awt.BorderLayout.WEST);
	}// </editor-fold>//GEN-END:initComponents

	private void onQuit(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_onQuit
		// Save all Lines to DB and change to SELECT_GAME
		TravelSalesViewController.getInstance().quit(pnPoints.getLines());

		// TODO write playstatistic

	}// GEN-LAST:event_onQuit

	private void onRestart(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_onRestart
		// Delete all lines
		TravelSalesViewController.getInstance().restartGame();
	}// GEN-LAST:event_onRestart

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel lbHighscore;
	private javax.swing.JLabel lbLength;
	private javax.swing.JPanel pnButtons;
	private javax.swing.JPanel pnCenter;
	private javax.swing.JPanel pnConstrains;
	private javax.swing.JPanel pnGame;
	private javax.swing.JPanel pnHighscore;
	private at.tug.oad.travelsales.view.gui.GamePanel pnPoints;
	private javax.swing.JPanel pnWest;

	// End of variables declaration//GEN-END:variables

	void setBaseGame(IBaseGame selectedBaseGame) {
		pnPoints.setGame(selectedBaseGame);
	}

	void clearLines() {
		this.pnPoints.clearLines();
		updateUI();
	}

	void setActualLineLenght(double length) {
		lbLength.setText("Length: " + String.format("%.2f", length) + "%, Points: " + (int) length * 100);
	}

	public void setPlayStatistic(IPlayStatistic p) {
		String text = "<HTML><b>Highscore:</b>" + p.getScore() + "</HTML>";
		lbHighscore.setText(text);
	}
}
