/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates and open the template
 * in the editor.
 */
package at.tug.oad.travelsales.view.gui;

import javax.swing.JFileChooser;
import javax.swing.JPanel;

import at.tug.oad.travelsales.controller.TravelSalesViewController;
import at.tug.oad.travelsales.model.IPoint;

/**
 *
 * @author Martin
 */
public class PointInfoPanel extends javax.swing.JPanel {

	private IPoint point;
	private JPanel panelToUpdate;

	/**
	 * Creates new form PointInfoPanel
	 */
	public PointInfoPanel() {
		initComponents();
	}

	public void setPoint(IPoint point) {
		if (point != null) {
			this.point = point;

			tfPointName.setText(point.getName());
			tfPointPositionX.setText(String.format("%d", (int) (point.getX() * 100)));
			tfPointPositionY.setText(String.format("%d", (int) (point.getY() * 100)));
			tfPointIconPath.setText(point.getIconPath());

		}
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		jPanel1 = new javax.swing.JPanel();
		jLabel2 = new javax.swing.JLabel();
		tfPointName = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		tfPointPositionX = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		tfPointIconPath = new javax.swing.JTextField();
		btSearchFile = new javax.swing.JButton();
		btSave = new javax.swing.JButton();
		jLabel5 = new javax.swing.JLabel();
		tfPointPositionY = new javax.swing.JTextField();

		setLayout(new java.awt.BorderLayout());

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Point Info:"));
		jPanel1.setLayout(new java.awt.GridBagLayout());

		jLabel2.setText("Point name:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
		jPanel1.add(jLabel2, gridBagConstraints);

		tfPointName.setColumns(15);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridwidth = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		jPanel1.add(tfPointName, gridBagConstraints);

		jLabel3.setText("Position x (in %):");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
		jPanel1.add(jLabel3, gridBagConstraints);

		tfPointPositionX.setColumns(5);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.gridwidth = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		jPanel1.add(tfPointPositionX, gridBagConstraints);

		jLabel4.setText("Icon:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
		jPanel1.add(jLabel4, gridBagConstraints);

		tfPointIconPath.setColumns(15);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		jPanel1.add(tfPointIconPath, gridBagConstraints);

		btSearchFile.setText("...");
		btSearchFile.setMaximumSize(new java.awt.Dimension(25, 23));
		btSearchFile.setMinimumSize(new java.awt.Dimension(25, 23));
		btSearchFile.setPreferredSize(new java.awt.Dimension(25, 23));
		btSearchFile.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onSearch(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 2;
		gridBagConstraints.gridy = 3;
		jPanel1.add(btSearchFile, gridBagConstraints);

		btSave.setText("Save");
		btSave.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onSave(evt);
			}
		});
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 4;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
		jPanel1.add(btSave, gridBagConstraints);

		jLabel5.setText("Position y (in %):");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
		jPanel1.add(jLabel5, gridBagConstraints);

		tfPointPositionY.setColumns(5);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.gridwidth = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		jPanel1.add(tfPointPositionY, gridBagConstraints);

		add(jPanel1, java.awt.BorderLayout.CENTER);
	}// </editor-fold>//GEN-END:initComponents

	private void onSave(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_onSave

		TravelSalesViewController.getInstance().updatePoint(point, p -> {
			p.setName(tfPointName.getText());
			p.setX(Double.parseDouble(tfPointPositionX.getText()) / 100);
			p.setY(Double.parseDouble(tfPointPositionY.getText()) / 100);
			p.setIconPath(tfPointIconPath.getText());
		});
		if (panelToUpdate != null) {
			panelToUpdate.updateUI();
		}
	}// GEN-LAST:event_onSave

	private void onSearch(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_onSearch
		try {
			JFileChooser chooser = new JFileChooser(tfPointIconPath.getText());
			if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
				tfPointIconPath.setText(chooser.getSelectedFile().getCanonicalPath());
				point.setIconPath(chooser.getSelectedFile().getCanonicalPath());
			}
		} catch (Exception e) {
			TravelSalesViewController.getInstance().showMessageDialog("Error", e.getMessage(), MessageType.ERROR);
		}

	}// GEN-LAST:event_onSearch

	public void setPanelToUpdate(JPanel panel) {
		this.panelToUpdate = panel;
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btSave;
	private javax.swing.JButton btSearchFile;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JTextField tfPointIconPath;
	private javax.swing.JTextField tfPointName;
	private javax.swing.JTextField tfPointPositionX;
	private javax.swing.JTextField tfPointPositionY;
	// End of variables declaration//GEN-END:variables
}
