/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates and open the template
 * in the editor.
 */
package at.tug.oad.travelsales.view.gui;

import javax.swing.JOptionPane;

import at.tug.oad.travelsales.controller.TravelSalesViewController;

/**
 *
 * @author Martin
 */
public class RegistrationPanel extends javax.swing.JPanel {

	/**
	 * Creates new form RegistrationPanel
	 */
	public RegistrationPanel() {
		initComponents();

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		jPanel1 = new javax.swing.JPanel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		tfFirstName = new javax.swing.JTextField();
		tfLastName = new javax.swing.JTextField();
		tfUserName = new javax.swing.JTextField();
		pfPassword1 = new javax.swing.JPasswordField();
		pfPassword2 = new javax.swing.JPasswordField();
		jLabel6 = new javax.swing.JLabel();
		tfEMail = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		jSeparator1 = new javax.swing.JSeparator();
		jPanel2 = new javax.swing.JPanel();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();

		setLayout(new java.awt.BorderLayout());

		jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Please enter the following informations:"));
		jPanel1.setLayout(new java.awt.GridBagLayout());

		jLabel1.setText("First Name:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
		jPanel1.add(jLabel1, gridBagConstraints);

		jLabel2.setText("Last Name:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
		jPanel1.add(jLabel2, gridBagConstraints);

		jLabel3.setText("Account name (Username):");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
		jPanel1.add(jLabel3, gridBagConstraints);

		jLabel4.setText("Password:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 4;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
		jPanel1.add(jLabel4, gridBagConstraints);

		jLabel5.setText("Confirm Password:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 5;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
		jPanel1.add(jLabel5, gridBagConstraints);

		tfFirstName.setColumns(25);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
		jPanel1.add(tfFirstName, gridBagConstraints);

		tfLastName.setColumns(25);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 1;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
		jPanel1.add(tfLastName, gridBagConstraints);

		tfUserName.setColumns(25);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 2;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
		jPanel1.add(tfUserName, gridBagConstraints);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 4;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
		jPanel1.add(pfPassword1, gridBagConstraints);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 5;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
		gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
		jPanel1.add(pfPassword2, gridBagConstraints);

		jLabel6.setText("E-Mail adress:");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
		gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
		jPanel1.add(jLabel6, gridBagConstraints);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 1;
		gridBagConstraints.gridy = 3;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(0, 5, 5, 0);
		jPanel1.add(tfEMail, gridBagConstraints);

		jLabel7.setText("You need to enter a valid e-mail adress to reset your password!");
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 7;
		gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
		jPanel1.add(jLabel7, gridBagConstraints);
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.gridx = 0;
		gridBagConstraints.gridy = 6;
		gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
		jPanel1.add(jSeparator1, gridBagConstraints);

		add(jPanel1, java.awt.BorderLayout.CENTER);

		jPanel2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

		jButton1.setText("Create Account");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1onCreateAccount(evt);
			}
		});
		jPanel2.add(jButton1);

		jButton2.setText("Cancel");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				onCancel(evt);
			}
		});
		jPanel2.add(jButton2);

		add(jPanel2, java.awt.BorderLayout.SOUTH);
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1onCreateAccount(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1onCreateAccount
		try {
			String data = "";
			data += "First name: " + tfFirstName.getText() + "\n";
			data += "Last name: " + tfLastName.getText() + "\n";
			data += "User name: " + tfUserName.getText() + "\n";
			int confirm = JOptionPane.showConfirmDialog(this, "Your account data:\n\n" + data, "Please Confirm", JOptionPane.OK_CANCEL_OPTION);

			if (confirm == JOptionPane.OK_OPTION) {
				String firstname, lastname, accountname, password1, password2, email;
				firstname = tfFirstName.getText();
				lastname = tfLastName.getText();
				accountname = tfUserName.getText();
				password1 = new String(pfPassword1.getPassword());
				password2 = new String(pfPassword2.getPassword());
				email = tfEMail.getText();

				TravelSalesViewController.getInstance().saveRegistration(firstname, lastname, accountname, password1, password2, email);
			}
		} catch (Exception e) {
			JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
		}

	}// GEN-LAST:event_jButton1onCreateAccount

	private void onCancel(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_onCancel
		TravelSalesViewController.getInstance().cancel();
	}// GEN-LAST:event_onCancel

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JSeparator jSeparator1;
	private javax.swing.JPasswordField pfPassword1;
	private javax.swing.JPasswordField pfPassword2;
	private javax.swing.JTextField tfEMail;
	private javax.swing.JTextField tfFirstName;
	private javax.swing.JTextField tfLastName;
	private javax.swing.JTextField tfUserName;
	// End of variables declaration//GEN-END:variables
}
